### ISSUE TITLE
Error when running simple test using Grails 2.5.3

### ISSUE THREAD

**Issue by luciano-fiandesio** [grails/grails-datastore-test-support#5]
Hello,

I’m using **Grails 2.5.3** and trying to use the **grails-datastore-test-support**’s `HibernateTestMixin`.

This is my test:

```
import grails.test.mixin.TestMixin
import spock.lang.Specification
import grails.test.mixin.gorm.Domain
import grails.test.mixin.hibernate.HibernateTestMixin
import com.Project

@TestMixin(HibernateTestMixin)
@Domain(Project)
class ProjectSpec extends Specification {

    void "Test count project" () {

        expect: "Test execute Hibernate count query"
            Project.count() == 0

    }
```

}

When running the test from command line, I get the following exception:

```
| Failure:  Test count people(com.csg.ept.cssdf.pad.domain.ProjectHibernateSpec)                                                                                                 

|  org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.grails.gorm.hibernate.internal.POST_INIT_BEAN-dataSource': Invocation of init method failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hibernateDatastore': Cannot resolve reference to bean 'grailsDomainClassMappingContext' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsDomainClassMappingContext': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.grails.datastore.gorm.config.GrailsDomainClassMappingContext]: Constructor threw exception; nested exception is java.lang.NullPointerException                                    

        at grails.test.runtime.GrailsApplicationTestPlugin$1.initializeContext(GrailsApplicationTestPlugin.groovy:118)                                                          

        at grails.test.runtime.GrailsApplicationTestPlugin.createMainContext(GrailsApplicationTestPlugin.groovy:123)                                                            

        at grails.test.runtime.GrailsApplicationTestPlugin.initGrailsApplication(GrailsApplicationTestPlugin.groovy:97)                                                         

        at grails.test.runtime.GrailsApplicationTestPlugin.onTestEvent(GrailsApplicationTestPlugin.groovy:327)                                                                   

        at grails.test.runtime.TestRuntime.deliverEvent(TestRuntime.groovy:295)                                                                                                 

        at grails.test.runtime.TestRuntime.executeEventLoop(TestRuntime.groovy:280)                                                                                             

        at grails.test.runtime.TestRuntime.processEvents(TestRuntime.groovy:265)                                                                                                 

        at grails.test.runtime.TestRuntime.doPublishEvent(TestRuntime.groovy:238)                                                                                               

        at grails.test.runtime.TestRuntime.publishEvent(TestRuntime.groovy:211)                                                                                                 

        at grails.test.runtime.TestRuntime.getValue(TestRuntime.groovy:122)                                                                                                      

        at grails.test.runtime.GrailsApplicationTestPlugin.onTestEvent(GrailsApplicationTestPlugin.groovy:320)                                                                  

        at grails.test.runtime.TestRuntime.deliverEvent(TestRuntime.groovy:295)                                                                                                 

        at grails.test.runtime.TestRuntime.processEvents(TestRuntime.groovy:264)                                                                                                 

        at grails.test.runtime.TestRuntime.doPublishEvent(TestRuntime.groovy:248)                                                                                                

        at grails.test.runtime.TestRuntime.publishEvent(TestRuntime.groovy:211)                                                                                                 

        at grails.test.runtime.TestRuntimeJunitAdapter.before(TestRuntimeJunitAdapter.groovy:109)                                                                               

        at grails.test.runtime.TestRuntimeJunitAdapter$1$2.evaluate(TestRuntimeJunitAdapter.groovy:47)                                                                           

        at org.spockframework.runtime.extension.builtin.TestRuleInterceptor.intercept(TestRuleInterceptor.java:38)                                                              

        at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)                                                                              

        at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:88)                                                                               

        at org.spockframework.runtime.extension.builtin.AbstractRuleInterceptor$1.evaluate(AbstractRuleInterceptor.java:37)                                                     

        at grails.test.runtime.TestRuntimeJunitAdapter$3$4.evaluate(TestRuntimeJunitAdapter.groovy:76)                                                                          

        at org.spockframework.runtime.extension.builtin.ClassRuleInterceptor.intercept(ClassRuleInterceptor.java:38)                                                            

        at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)                                                                              

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hibernateDatastore': Cannot resolve reference to bean 'grailsDomainClassMappingContext' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsDomainClassMappingContext': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.grails.datastore.gorm.config.GrailsDomainClassMappingContext]: Constructor threw exception; nested exception is java.lang.NullPointerException                                                        

        at grails.orm.bootstrap.HibernateDatastoreSpringInitializer$PostInitializationHandling.afterPropertiesSet(HibernateDatastoreSpringInitializer.groovy:259)               

        ... 24 more                                                                                                                                                              

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsDomainClassMappingContext': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.grails.datastore.gorm.config.GrailsDomainClassMappingContext]: Constructor threw exception; nested exception is java.lang.NullPointerException                                                                                                                

        ... 25 more                                                                                                                                                              

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.grails.datastore.gorm.config.GrailsDomainClassMappingContext]: Constructor threw exception; nested exception is java.lang.NullPointerException                                                                                                                       

        ... 25 more                                                                                                                                                              

Caused by: java.lang.NullPointerException                                                                                                                                       

        at org.grails.datastore.gorm.config.GrailsDomainClassPersistentEntity.getName(GrailsDomainClassPersistentEntity.java:124)                                               

        at org.grails.datastore.mapping.model.AbstractMappingContext.registerEntityWithContext(AbstractMappingContext.java:234)                                                 

        at org.grails.datastore.mapping.model.AbstractMappingContext.addPersistentEntityInternal(AbstractMappingContext.java:219)                                               

        at org.grails.datastore.mapping.model.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:206)                                                       

        at org.grails.datastore.gorm.config.GrailsDomainClassPersistentEntity.configureAssociation(GrailsDomainClassPersistentEntity.java:271)                                  

        at org.grails.datastore.gorm.config.GrailsDomainClassPersistentEntity.createOneToOne(GrailsDomainClassPersistentEntity.java:251)                                         

        at org.grails.datastore.gorm.config.GrailsDomainClassPersistentEntity.initialize(GrailsDomainClassPersistentEntity.java:98)                                             

        at org.grails.datastore.mapping.model.AbstractMappingContext.initializePersistentEntity(AbstractMappingContext.java:250)                                                

        at org.grails.datastore.mapping.model.AbstractMappingContext.addPersistentEntities(AbstractMappingContext.java:183)                                                      

        at org.grails.datastore.gorm.config.GrailsDomainClassMappingContext.<init>(GrailsDomainClassMappingContext.java:47)                                                     

        ... 25 more                                                                                                                                                              

| Completed 1 unit test, 1 failed in 0m 6s                                                                                                                                       

| Tests FAILED  - view reports in C:\Apps\projects\aaa-webapp\target\test-reports                                                                                             
```

I’m using the following version:

`test "org.grails:grails-datastore-test-support:1.0.2-grails-2.4"`

Please let me know if you need more information

**Comment by animator013** [comment]
Hi. I have the same problem. Is there any fix for this? I cannot use HibernateTestMixin in unit tests.

**Comment by verglor** [comment]
I have the same problem.

**Comment by olandere** [comment]
Same issue with Grails 2.5.5.

**Comment by ntung** [comment]
I have the same problem with Grails 2.5.5

**Comment by federicobaiocco** [comment]
Same with Grails 2.5.6

**Comment by sourcerunner** [comment]
Same problem with grails 5.0.1 in 2024

**Comment by jamesfredley** [comment]
I'd look at GORM testing support in https://testing.grails.org/latest/guide/index.html
